[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[profile.release]
debug = 1

[workspace]
members = ["crates/newday"]

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[dependencies]
counter = "0.6.0"
derive-new = {version="*", default-features = false}
grid = "0.15.0"
inline_colorization = "0.1.6"
itertools = "0.13.0"
rayon = "1.10.0"
regex = {version="*", default-features = false}
strum = { version = "0.26.3", features = ["derive"] }