[package]
name = "aoc2024"
version.workspace = true
edition.workspace = true
publish = false

[workspace]
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[lints]
workspace = true

[lib]
doctest = false

[profile.release]
debug = 1

[dependencies]
counter = "0.6.0"
derive-new = {version="*", default-features = false}
grid = "0.15.0"
inline_colorization = "0.1.6"
itertools = "0.13.0"
rayon = "1.10.0"
regex = {version="*", default-features = false}
strum = { version = "0.26.3", features = ["derive"] }