[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
counter = "0.6.0"
derive-new = {version="*", default-features = false}
grid = "0.15.0"
inline_colorization = "0.1.6"
itertools = "0.13.0"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
tinytemplate = "1.2.1"
