[package]
name = "newday"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
derive-new.workspace = true
serde = { version = "1.0.215", features = ["derive"] }
tinytemplate = "1.2.1"
